### ISSUE TITLE
Lora 868 module

### ISSUE THREAD

**Issue by berkhoff** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#10]
Just a question. Why exactly does the Lora 868 module require an alternative version and a different library (LMIC) ? Doesn't the standard seeduino library work with this module?

I have the 868 module but failed to make the hardware mod you suggested. The DIO1 pin broke off. The module still seems to work and I would like to use it with the standard LoRaWan library. 

Mark Berkhoff

**Comment by Bjoerns-TB** [comment]
Hi,

the modules are completely different. The LoRaWAN is connect via UART and has an build in LoRaWAN stack. The 868 is connected via SPI and needs the LMIC library. The LoRaWAN module uses AT commands for communication, which are translated by the seeduino library. Because the modules are so different i made two versions. 

Without DIO1 connected the module can't be used in LoRaWAN networks. Can you post a picture of the broken pin?

**Comment by berkhoff** [comment]
Hi, Thank you so much for the update. That makes sense and I think I need to scrap the module or use it for Lora only. Will order a new module that includes the LoRaWan functionality. 
Attached is a picture of the broken module (due to my poor soldering skills).

![5CE6E9BE-E246-4866-9CD0-93AA57F28B36_1_105_c](https://user-images.githubusercontent.com/7255708/107025230-68c7f180-67a9-11eb-9225-78d61d6454cf.jpeg)

**Comment by Bjoerns-TB** [comment]
Oh i see, sorry for that.
